### ISSUE TITLE
Frame Drop When GameLoop Starts

### ISSUE THREAD

**Issue by JeFi-314** [gitAdrianK/SwitchBlocks#16]
After the latest update on the Workshop, I encountered significant frame drops (~25 frames) at the start of the game while trying to record a GotIB TAS run. The frame drop also happens when I start or restart the game manually.

After update: [Video link](https://youtu.be/0kgCoya9Y4Q?t=8s)
Before update: [Video link](https://youtu.be/yeqv84G9t1s?t=11)
I built a local version for testing, and I found that the issue started after commit 258797. I confirmed that:

Commit 84e55a: No frame drop issues. I used this version to record my new TAS run.
Commit 258797: No frame drop issues, but the game is not fully playable.

I also tested another map (Babe of Transcension) and did not encounter any frame drops.

**Comment by gitAdrianK** [comment]
I reverted to 84e55a bringing over some changes/bug fixes that should not influence framerate.
[6882aad](https://github.com/gitAdrianK/SwitchBlocks/commit/6882aadc8a2721d7eef381c2c9e25310625df466)
Let me know how it goes.

**Comment by JeFi-314** [comment]
The frame drop issue has been resolved on the Workshop. Thank you!

**Comment by gitAdrianK** [comment]
Nice, I will close the issue then. Should a new problem arise just let me know!
